version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: continuous_integration_postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta para conex√£o AMQP
      - "15672:15672" # Porta para o painel web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    volumes:
      - ./rabbitmq-init.sh:/docker-entrypoint-init.d/rabbitmq-init.sh
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  consumidor:
    build:
      context: .
      dockerfile: Dockerfile.consumidor
    container_name: consumidor
    ports:
      - "50050:50050"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy

  rastreamento-service:
    build:
      context: ./rastreamento-service
    container_name: rastreamento_service
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}

  auth-service:
    build:
      context: ./auth-service
    container_name: auth_service
    ports:
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}

  pedido-service:
    build:
      context: ./pedido-service
    container_name: pedido_service
    ports:
      - "50061:50061"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}

  promotion-service:
    build:
      context: ./promotion-service
    container_name: promotion_service
    ports:
      - "50053:50053"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}

  segmentation-service:
    build:
      context: ./segmentation-service
    container_name: segmentation_service
    ports:
      - "50054:50054"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}

  gateway:
    build:
      context: ./gateway
    container_name: api_gateway
    ports:
      - "50092:50092"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
volumes:
  pgdata:
